Algoritmo "SomaDosQuadrados"
// Disciplina   : Lógica de Programação com visualG
// Professor    : Jailson
// Descrição    : Lê três valores e apresenta a soma dos quadrados de cada um.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual   : 19/04/2026
Var
A, B, C, resultado: real

Inicio
Escreval("Soma dos Quadrados de Três Valores")
Escreva("Digite o valor de A: ")
Leia(A)
Escreva("Digite o valor de B: ")
Leia(B)
Escreva("Digite o valor de C: ")
Leia(C)

resultado <- (A ^ 2) + (B ^ 2) + (C ^ 2)

Escreva("O resultado da soma dos quadrados é: ", resultado)
Fimalgoritmo