Algoritmo "QuadradoDaSoma"
// Disciplina   : Lógica de Programação com visualG
// Professor    : Jailson
// Descrição    : Lê três valores e apresenta o quadrado da soma dos três valores.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual   : 19/04/2026
Var
A, B, C, resultado: real

Inicio
Escreval("Cálculo do Quadrado da Soma")
Escreva("Digite o valor de A: ")
Leia(A)
Escreva("Digite o valor de B: ")
Leia(B)
Escreva("Digite o valor de C: ")
Leia(C)

resultado <- (A + B + C) ^ 2

Escreva("O quadrado da soma dos três valores é: ", resultado)
Fimalgoritmo