Algoritmo "Antecessor"
// Disciplina  : Lógica de Programação com visualG
// Professor   : Jailson
// Descrição   : Lê um valor e escreve o seu antecessor.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 22/04/2026
Var
valor, resultado: inteiro

Inicio
Escreva("Digite um número inteiro: ")
Leia(valor)
resultado <- valor - 1
Escreval("O antecessor de ", valor, " é: ", resultado)
Fimalgoritmo