Algoritmo "Metros-Para-Centimetros"
// Disciplina  : Lógica de Programação com visualG
// Professor   : Jailson
// Descrição   : Converte uma medida em metros para centímetros.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 22/04/2026
Var
metros, centimetros: real

Inicio
Escreva("Digite o valor em metros (m): ")
Leia(metros)
centimetros <- metros * 100
Escreval(metros, "m equivale a ", centimetros, "cm.")
Fimalgoritmo