Algoritmo "Comparacao-valor-10"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Lê um valor e verifica se é maior que 10.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 22/04/2026
Var
valor: real

Inicio
Escreva("Digite um valor: ")
Leia(valor)
Se (valor > 10) entao
   Escreval("É MAIOR QUE 10!")
Senao
   Escreval("NÃO É MAIOR QUE 10!")
Fimse

Fimalgoritmo