Algoritmo "Positivo-ou-negativo"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Lê um valor e verifica se é positivo ou negativo.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 22/04/2026
Var
valor: real

Inicio
Escreva("Digite um valor: ")
Leia(valor)
Se (valor >= 0) entao
   Escreval("Positivo")
Senao
   Escreval("Negativo")
Fimse

Fimalgoritmo