Algoritmo "Area-Circulo-Simples"
// Disciplina  : Lógica de Programação com visualG
// Professor   : Jailson
// Descrição   : Calcula a área de um círculo (PI * R^2).
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 22/04/2026
Var
raio, area: real

Inicio
Escreva("Digite o raio do círculo: ")
Leia(raio)

area <- 3.14159 * (raio * raio)

Escreval("A área do círculo é: ", area:5:2)
Fimalgoritmo