Algoritmo "Area-Quadrado-Dobro"
// Disciplina  : Lógica de Programação com visualG
// Professor   : Jailson
// Descrição   : Calcula a área de um quadrado e mostra o dobro do resultado.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 22/04/2026
Var
lado, area, dobro: real

Inicio
Escreva("Digite o lado do quadrado: ")
Leia(lado)
area <- lado * lado
dobro <- area * 2
Escreval("Área do quadrado: ", area)
Escreval("O dobro da área é: ", dobro)
Fimalgoritmo