Algoritmo "Area-Retangulo"
// Disciplina  : Lógica de Programação com visualG
// Professor   : Jailson
// Descrição   : Calcula a área de um retângulo (base x altura).
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 22/04/2026
Var
base, altura, area: real

Inicio
Escreva("Digite a base do retângulo: ")
Leia(base)
Escreva("Digite a altura do retângulo: ")
Leia(altura)
area <- base * altura
Escreval("A área do retângulo é: ", area)
Fimalgoritmo