Algoritmo "Validacao-nota"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Recebe a nota de um aluno em Cálculo 1
//               e valida se foi aprovado.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 18/04/2026
Var
nota: real

Inicio
Escreval("Validação de Nota")
Escreva("Digite a nota do aluno em Cálculo 1: ")
Leia(nota)
Se (nota >= 6.0) entao
   Escreval("Aprovado")
Fimse
Fimalgoritmo