Algoritmo "Teste-paridade"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Recebe um número inteiro e verifica se é par
//               usando o operador MOD.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 18/04/2026
Var
numero: inteiro

Inicio
Escreval("Teste de Paridade")
Escreva("Digite um número inteiro: ")
Leia(numero)
Se (numero % 2 = 0) entao
   Escreval("O número é par")
Fimse
Fimalgoritmo