Algoritmo "Multiplos"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Recebe dois números inteiros e verifica se
//               o primeiro é múltiplo do segundo.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 18/04/2026
Var
numero1: inteiro
numero2: inteiro

Inicio
Escreval("Múltiplos")
Escreva("Digite o primeiro número inteiro: ")
Leia(numero1)
Escreva("Digite o segundo número inteiro: ")
Leia(numero2)
Se (numero1 % numero2 = 0) entao
   Escreval("O primeiro é múltiplo do segundo")
Fimse
Fimalgoritmo