Algoritmo "Area-quadrado"
// Disciplina   : Lógica de Programação com visualG
// Professor   : Jailson
// Descrição   : Recebe medidas dos lados de um quadrado e calcula a área.
// Autor(a)    : Matheus
// Data atual  : 20/03/2026
Var
// Seção de Declarações das variáveis 
numero1: real
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Área do quadrado")
Escreva("Digite a medida do lado do quadrado: ")
Leia(numero1)
resultado <- numero1 * numero1
Escreva("A área do quadrado é:", resultado)
Fimalgoritmo