Algoritmo "Perimetro-quadrado"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Recebe o valor do lado de um quadrado e calcula o perímetro.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 18/04/2026
Var
lado: real
perimetro: real

Inicio
Escreval("Perímetro do Quadrado")
Escreva("Digite o valor do lado do quadrado: ")
Leia(lado)
perimetro <- 4 * lado
Escreval("O perímetro do quadrado é: ", perimetro)
Fimalgoritmo