Algoritmo "Area-retangulo"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Recebe valores da base e da altura de um retângulo e
//               calcula sua área.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 18/04/2026
Var
base: real
altura: real
area: real

Inicio
Escreval("Área do Retângulo")
Escreva("Digite a base do retângulo: ")
Leia(base)
Escreva("Digite a altura do retângulo: ")
Leia(altura)
area <- base * altura
Escreval("A área do retângulo é: ", area)
Fimalgoritmo