Algoritmo "Area-triangulo"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Recebe valores da base e da altura de um
//              triângulo e calcula sua área.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 18/04/2026
Var
base: inteiro
altura: inteiro
area: real

Inicio
Escreval("Área do Triângulo")
Escreva("Digite a base do triângulo: ")
Leia(base)
Escreva("Digite a altura do triângulo: ")
Leia(altura)
area <- (base * altura) / 2
Escreval("A área do triângulo é: ", area)
Fimalgoritmo