Algoritmo "Area-paralelogramo"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Recebe a base e a altura de um paralelogramo
//               e calcula sua área.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 18/04/2026
Var
base: inteiro
altura: inteiro
area: inteiro

Inicio
Escreval("Área do Paralelogramo")
Escreva("Digite a base do paralelogramo: ")
Leia(base)
Escreva("Digite a altura do paralelogramo: ")
Leia(altura)
area <- base * altura
Escreval("A área do paralelogramo é: ", area)
Fimalgoritmo