Algoritmo "Par-ou-Impar"
// Disciplina   : Lógica de Programação com VisualG
// Professor   : Jailson
// Descrição   : Recebe um número inteiro e verifica se é par ou ímpar.
// Autor(a)    : Matheus Nascimento Silveira
// Data atual  : 18/04/2026
Var
numero: inteiro

Inicio
Escreval("Par ou Ímpar")
Escreva("Digite um número inteiro: ")
Leia(numero)
Se (numero % 2 = 0) entao
   Escreval("Par")
Senao
   Escreval("Ímpar")
Fimse
Fimalgoritmo